### ISSUE TITLE
As a Beacon Südtirol PM I want to have the publication pipeline of the gamification module backend online in order to be able to publish the first MVP of the backend.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/beacon-gamification-backend#1]

**Comment by bertolla** [comment]
I requested a pull request from Belka with setup guide but did not get any yet. I guess it's not ready yet.

**Comment by bertolla** [comment]
Alex Lanz will start implement pipelines

**Comment by bertolla** [comment]
App is available on https://play.google.com/store/apps/details?id=it.bz.beacon.beaconsuedtiroladventure
Pipeline is not yet implemented and the source code is not up to date with the latest Belka release.
**Important**: to do the release we had to pass the keepass store key to Belka.

**Comment by bertolla** [comment]
Pipelines can not be setup, since no documentation provided (see https://github.com/noi-techpark/beacon-gamification-module/tree/development). AlexL. is working on it by guessing some things and using know how that was provided from Belka by phone.(see https://github.com/noi-techpark/beacon-gamification-backend/pull/3)

**Comment by sseppi** [comment]
The backend has been tested and now seems to work everything fine. Putting it on prodoction can we swith also the API of the Südtirol Adventure or do I have to create a dedicated issue for it?
